### ISSUE TITLE
Install compiled method in context of a package

### ISSUE THREAD

**Issue by herby** [amber-smalltalk/amber#1125]
Now, compiler installs the compiled method in context of a Compiler-Something package - where the eval actually gets run. This does not break anything, as all packages (unless you mix packages from old versions with packages from current version) have same set of local variables, With #1068, each package will have its distinct inner environment. Thus, installation of methods / export of packages / maybe some more need to be changed, so that the installation eval is run always inside the package context.

**Comment by herby** [comment]
@NicolasPetton Hi! I would like to have you guess as how big complication can this (each package having its own set of local variables, not just the universally shared ones with smalltalk api, nil, etc.) could this bring to ASTInterpreter (it should take this into account and interpret each method in context of the package the method was defined in).

**Comment by NicolasPetton** [comment]
@herby hi! 

I guess it depends which variable would be package-specific. Can you elaborate a bit more?

**Comment by herby** [comment]
Hi. Well, even now those three ($core, nil, $recv) are all package-specific, just they happen to have the same values for all packages, so it does not matter. But with this, a package can have more variables of its own (for example, with per-package dependences. package Web can have its own local variable jQuery, while other won't even have access to it). IOW, packages will import external dependencies and reify them as local variables accessible only in the code in the package. For ASTInterpreter (or, reflection in general) to work, each package should be able to export its local context and/or eval_in_the_context function). We can assume package will do that, but how big problems could this (per-package context in which the code is run) bring to ASTInterpreter?

Nicolas Petton wrote:
> @herby <https://github.com/herby> hi!
>
> I guess it depends which variable would be package-specific. Can you 
> elaborate a bit more?
>
> —
> Reply to this email directly or view it on Gi
tHub 
> <https://github.com/amber-smalltalk/amber/issues/1125#issuecomment-69425522>.
>

**Comment by herby** [comment]
Blocks on #1135, also coupled to #1136.
