### ISSUE TITLE
JSObjectProxy isNil/isNotNil extension

### ISSUE THREAD

**Issue by HeSe** [amber-smalltalk/amber#1128]
Would it be possible to add isNil and isNotNil to JSObjectProxy ?

isNil
  ^false

isNotNil
  ^true

**Comment by herby** [comment]
Use ifNil: family for the moment, it is inlined.
BTW if you want isNil and isNotNil there, you probably want it up on ProtoObject.,, but both `ProtoObject` and `JSObjectProxy` should have minimal API, not to stand in way of the proxied object...

**Comment by herby** [comment]
See also #184. I think isNil and notNil (BTW, we use `notNil`, not `isNotNil`) should be inlined as well... in that case, they should be in `ProtoObject`.

**Comment by herby** [comment]
Could this be closed in favour of #1129?

**Comment by HeSe** [comment]
sure

**Comment by sebastianconcept** [comment]
great! +1 @herby
