### ISSUE TITLE
Move `xxxNil` family of selectors into `ProtoObject`

### ISSUE THREAD

**Issue by herby** [amber-smalltalk/amber#1129]
The `ifNil:ifNotNil:` family is inlined in the compiler, so it can take any reciever, it does not discriminate. That's why I think these four should be moved into `ProtoObject`.

Then there are `isNil` and `notNil`, which #1128 requires to be present in non-`Objects` as well, and which are hopefully going to be inlined, too (#184), which means, they should be in `ProtoObject` as well.

**Comment by sebastianconcept** [comment]
I would be a user of `isNil` and `notNil` in non-Amber-Objects

I currently need them so I've set it in the jsproxy as extended methods but yeah, having them in the core sounds right and inlined sounds great

**Comment by sebastianconcept** [comment]
great!

**Comment by herby** [comment]
@HeSe Do you want to do it?
