### ISSUE TITLE
amber version command, 0.14.2?

### ISSUE THREAD

**Issue by hhzl** [amber-smalltalk/amber#1131]
After running 

      npm -g uninstall amber-cli
      npm -g install amber-cli@bleedingedge

After

      amber version

I get

     Welcome to Amber version 0.14.0-0 (NodeJS 0.10.25)

I expected Amber version 0.14.2. Isn't there an automatic test for this?

**Comment by philippeback** [comment]
As Herby explained to me yesterday, amber-cli is 0.14 but amber core is
0.14.x

Look in the bower_components/amber/package.json (mine is not bleeding edge
but still 0.14.2

[philippeback@CENTOSDEV bower_components]$ cd amber
[philippeback@CENTOSDEV amber]$ ls
API-CHANGES.txt  CONTRIBUTING.md  jquery.amd.json  package.json  support
bower.json       favicon.ico      LICENSE          README.md
CHANGELOG        Gruntfile.js     local.amd.json   src
[philippeback@CENTOSDEV amber]$ cat package.json
{
  "name": "amber",
  "version": "0.14.2",
  "description": "An implementation of the Smalltalk language that runs on
top of the JS runtime.",
  "homepage": "http://amber-lang.net",
  "keywords": [
    "javascript",
    "smalltalk",
    "language",
    "compiler",
    "web"
...

HTH
Phil

**Comment by hhzl** [comment]
@philippeback Thank you
indeed bower_components/amber/bower.json and bower_components/amber/package.json both have

    {
        "name": "amber",
        "version": "0.14.2",

So I could successfully verify that I have the very latest version.

**Comment by mkroehnert** [comment]
@hhzl version 0.14.0 is shown since amber-cli is still using Amber 0.14.0 as can be seen in its [package.json](https://github.com/amber-smalltalk/amber/blob/master/external/amber-cli/package.json) file.
