### ISSUE TITLE
Make `heliosClass` generic by renaming method and protocol

### ISSUE THREAD

**Issue by sebastianconcept** [amber-smalltalk/amber#1132]
The method `heliosClass` is currently defined all around in the base code.

Needs to be moved to the Helios project.

**Comment by herby** [comment]
It cannot. Helios observes foreign frame / context. So extension methods do not help (they are local to running Helios itself).
Of course, you can find out some "clever" injecting of it based on names of the classes, but ... seems awkward, error prone, overall problematic.

**Comment by herby** [comment]
But maybe you can rename it "classRole" or "humanistClassCategory" or so ;-) and keep a list of known ones somewhere.

Sebastian Sastre wrote:

**Comment by sebastianconcept** [comment]
Well, they don't belong there.

I'm not getting what are the use for, I assume helios itself uses it. 

If the environment of the IDE is involved then it should be decoupled from Helios.

If it cannot be removed, then using `ideClass` as name would be better as it would allow to plug different IDEs including Helios which by the way would be great since I see the Helios detractors queue growing.

**Comment by herby** [comment]
It is used to denote what is the broad role of the class (genreic class, widget, collection, maybe something else). Helios uses it to select an icon. It is not helios-specific. It is a generic role of the class.

For the reasons mentioned, it is hard / error-prone to inject it externally, not to mention you may want your own code to have one of those, which is not predictable at all from outside.

So, ideally, some nice generic name is found for it and it is renamed (including the protocol).

Sebastian Sastre wrote:
> Well, they don't belong there.
>
> I'm not getting what are the use for, I assume helios itself uses it.
>
> If the environment of the IDE is involved then it should be decoupled 
> from Helios.
>
> If it cannot be removed, then using |ideClass| as name would be better 
> as it would allow to plug different IDEs including Helios which by the 
> way would be great since I see the Helios detractors queue growing.
>
> —
> Reply to this email directly or view it o
n GitHub 
> <https://github.com/amber-smalltalk/amber/issues/1132#issuecomment-70376199>.
>

**Comment by sebastianconcept** [comment]
It do not make any sense for Amber server apps and they are there for cosmetic reasons.

Having those methods in the base code for helios or any other IDE to display icons is a pretty poor design decision. Those methods simply do not belong to Amber, they belong to tools. Tools should deal with their challenges.

**Comment by herby** [comment]
It is impossible to do otherwise, if you want to be able to tag any class in your code with an IDE category. Just rename it to `ideTag` and everything's ok. In case the mechanism of selecting icon is hardcoded (isCollection ifTrue: ...) then yes, it can be in Helios. In case you want to have it generic and use polymorphism, use must to have this tag in those classes themselves.

Sebastian Sastre wrote:

**Comment by mkroehnert** [comment]
@herby is right.
This is a general way on how things like this are done in Smalltalk.
As an example, take a look at the methods in the `testing` protocol/category of the `Object` class in Pharo.

**Comment by sebastianconcept** [comment]
Can we rename it to `ideClass`?

**Comment by herby** [comment]
We can. Though I think it would be fine to use other thing than 'class' as it has narrower meaning in OOP. Tag, category, group, role, species, family, taxon?

Sebastian Sastre wrote:

**Comment by mkroehnert** [comment]
Maybe choose the method name according to what its result is used for?

**Comment by herby** [comment]
iconName? That's too narrow. It has broader meaning of "what kind of thing this is"? Well, apiKind can also be one possibility.

Manfred Kröhnert wrote:

**Comment by sebastianconcept** [comment]
What about `classTag`

**Comment by herby** [comment]
LGTM

Sebastian Sastre wrote:

**Comment by sebastianconcept** [comment]
great, thanks @herby

**Comment by herby** [comment]
Fixed by #1140.
