### ISSUE TITLE
Creating a tutorial

### ISSUE THREAD

**Issue by amroto** [amber-smalltalk/amber#1133]
I want to create  a tutorial for amber for creating an editable list can somebody help me similar to the Aida tutorial http://www.aidaweb.si/tutorial I just can't figure out what to change ?

**Comment by sebastianconcept** [comment]
Studying this might help you @amroto https://github.com/statonjr/Amber-ToDo-List

You should know that we are coordinating an effort to improve the Amber docs, your tutorial will be most welcome!

I wan to encourage you to write it and get it reviewed by our team among the rest of the docs here:

https://trello.com/b/PDYympel/amber-documentation

**Comment by mkroehnert** [comment]
Hi, this is not a report about an issue in Amber.
It would be nice if you could move this discussion to the mailinglist.

**Comment by amroto** [comment]
I already have a tutorial a counter tutorial on my profile https://github.com/amroto/Amber-Tutorial
do you have an IRC guys ?

**Comment by mkroehnert** [comment]
Yes, you can see the communication channels here: http://amber-lang.net/index.html#getinvolved
However, it seems that Gitter is currently used more frequently than IRC.

**Comment by amroto** [comment]
@sebastianconcept  https://github.com/amroto/Amber-Tutorial counter up to date
