### ISSUE TITLE
Missing dependency prevents compilation

### ISSUE THREAD

**Issue by sebastianconcept** [amber-smalltalk/amber#1145]
Since 0.14.3 new projects fail to complete the compilation done with `grunt`.

Here is the last part:

```
├── grunt-legacy-log@0.1.1 (underscore.string@2.3.3, lodash@2.4.1)
└── js-yaml@2.0.5 (esprima@1.0.4, argparse@0.1.16)
Running "amberc:all" (amberc) task
[Error: Dependency not found: jquery]

Running "amdconfig:app" (amdconfig) task

Running "requirejs:devel" (requirejs) task

Done, without errors.
 
The project should now be set up.
```

**Comment by sebastianconcept** [comment]
Thanks for the quick response on this

**Comment by mkroehnert** [comment]
Could you explain why a missing dependency should not lead to aborting compilation?
Either it is really missing and would lead to loading issues or it is a wrong dependency and should be removed.
Or did I miss something?

**Comment by herby** [comment]
If you set package's external (non-amber) dependencies via imports feature of 0.14.3, they get things like 'jquery' or 'bootstrap' in the dependency list. These dependencies, though, cannot be loaded in node. So if you use 'Web' as library for compilation of some file (very likely you do, 'Web' is used often, as is included as a library by default in `amber init`-created projects), amberc will try to load 'Web' and fail because of 'jquery' dependency.

So, missing dependency is now only written as a warning.

Manfred Kröhnert wrote:

**Comment by mkroehnert** [comment]
Thanks for the explanation.
Didn't know about this feature and its consequences but it makes perfect
sense :-)

**Comment by herby** [comment]
The exception thrown when dependency is missing is a good feature. Imports should be able to avoid loading for libraries in cli compiler in different way.

**Comment by herby** [comment]
@philippeback @sebastianconcept What do you think of different output of imports in .js files which would generate two files, as shown in #1151 (aff5bdd shows what is the difference in an example of Web package)? It then allows to fix this issue in a different way (715370c) by faking the imports module for libraries so it is not loaded. @mkroehnert I think the error for missing dependency is in fact useful and it is fine to be able to get it back.

**Comment by sebastianconcept** [comment]
@herby what are the implications of this new design in terms of added/removed complexity and build results?
I'm trying to understand the disadvantages or inconveniencies of going this way (not to be negative but to validate if it's worth or what we could improve)

**Comment by herby** [comment]
Sebastian Sastre wrote:
> @herby <https://github.com/herby> what are the implications of this 
> new design in terms of added/removed complexity and build results?

Build results: none (everything just build same as today)
Complexity: Sometimes there are two .js files for one .st (when package has imports)

OTOH, maybe it even takes a bit of complexity away when it clearly isolates implicit amber-level dependencies (ones that were there from 0.12 by default) from explicitly declared external imports (by adding them always via './Foo%Imports' into Foo.js's define call and writing them to separate file). For example, it's easier to recover from missing import load failure (just remove './Foo%Imports' from Foo.js, load, fix them in IDE (they are still shown in IDE)) and commit. With previous one, you would need to know what to remove and what to leave.

> I'm trying to understand the disadvantages or inconveniencies of going 
> this way (not to be negative but to validate if i
t's worth or what we 
> could improve)

Returning of old behaviour (error on actual missing dependency) is a plus. That was the reason for doing it in a less flat, thus easily fakeable layout.

Alternative I thought of today morning is to add pragmas (similar to ones for IDE data and contexts) that would wrap list of external dependencies in define call (it would make it uglier a bit, but who looks into .js file) which would be activated only when library is loaded for use inside amberc (and wherever else where external deps would be undesirable). That could keep it all in one file.

**Comment by herby** [comment]
Fixed via b27c73f.

**Comment by sebastianconcept** [comment]
Sounds interesting @herby 

Are we able to make it give good feedback on missing dependencies?

I'm worried about silly mistakes and the system leaving you without any clue

**Comment by herby** [comment]
???

Nothing changed as for missing dependency logging or these things.
There must be 0.14.4 out with this (though there is this compiler issue which should be solved as well, otherwise I don't see the reason for a release), then majority of people should upgrade, and then the old throw Error could go back (it would fail if someone has 0.14.3 because of Web.js in old format).

Sebastian Sastre wrote:

**Comment by sebastianconcept** [comment]
cool
