### ISSUE TITLE
"Parse error on line 1 column 47 : Unexpected character null"

### ISSUE THREAD

**Issue by TazeTSchnitzel** [amber-smalltalk/amber#1154]
http://amber-lang.net/learn.html DoIt button in Firefox

**Comment by herby** [comment]
Not a bug, You should read what's wriiten there. Especially on line 6.

**Comment by TazeTSchnitzel** [comment]
Ah, I see. Still, it's a really awful error message that suggests a bug in the implementation. There's no such thing as a null character.

**Comment by herby** [comment]
Issue an error in amber-smalltalk/trysmalltalk repo (that contains profstef course) that pressing DoIt button without clicking on sourcecode area nor selecting anything does this ugly error. Maybe it is just a matter of shifting focus on to the editbox or something similar.

**Comment by TazeTSchnitzel** [comment]
@herby alright, done! https://github.com/amber-smalltalk/trysmalltalk/issues/25
