### ISSUE TITLE
deployment with config.js file present.

### ISSUE THREAD

**Issue by hhzl** [amber-smalltalk/amber#1155]
From ML: Sat, 7h Feb "Deploy causes Helios not to work"

For deployment  do

      grunt deploy

Then only copy ``index.html`` and ``the.js`` to the deployment folder.

Check if there is an error if erroneously ``config.js`` is copied to the deployment folder in addition.

**Comment by herby** [comment]
??? What is this strange issue about?

**Comment by hhzl** [comment]
What you just mentioned on the ML

On Sunday, February 8, 2015 at 5:10:44 AM UTC-6, Herby wrote:

    Dňa 8. februára 2015 5:53:45 CET používateľ Blake McBride
<blak...@gmail.com> napísal:
    > Okay.  I found the problem.  The problem I reported occurs if you copy
    >
    > (deploy) the config.js file too.

    Yeah, I suspected that. But even then, it should not happen, as
config.js should have relative paths, so it should not be able to find
the IDE starter dialog in the mapped path, as it does not exist.
Deployment should work fine even with config.js. If it does not, it
may be a bug.

Somebody might want to check this.

**Comment by herby** [comment]
The wording and all is super strange. I am totally confused what this issue should be about.

Hannes Hirzel wrote:
> What you just mentioned on the ML
>
> On Sunday, February 8, 2015 at 5:10:44 AM UTC-6, Herby wrote:
>
> Dňa 8. februára 2015 5:53:45 CET používateľ Blake McBride
> <blak...@gmail.com> napísal:
> > Okay. I found the problem. The problem I reported occurs if you copy
> >
> > (deploy) the config.js file too.
>
> Yeah, I suspected that. But even then, it should not happen, as
> config.js should have relative paths, so it should not be able to find
> the IDE starter dialog in the mapped path, as it does not exist.
> Deployment should work fine even with config.js. If it does not, it
> may be a bug.
>
> Somebody might want to check this.
>
>
> On 2/8/15, Herbert Vojčík <notifications@github.com> wrote:
> > ??? What is this strange issue about?
> >
> > ---
> > Reply to this email directly or view it on GitHub:
> > 
> https://github.com/amber-smalltalk/amber/is
sues/1155#issuecomment-73408028

**Comment by hhzl** [comment]
Do the following test

1.   ``grunt deploy``
2.  Copy ``index.html``, ``the.js``, ``config.js`` into a deployment folder
3.  Open ``index.html``.
4. Check if the error Blake reported appereas
5.  If yes, this is an issue.
6. If no close this issue.

**Comment by herby** [comment]
Aha, so you don't yet know this is an issue, it just may be one. Ok.

Hannes Hirzel wrote:

**Comment by hhzl** [comment]
A distribution folder with
- index.html
- the.js
- config.js

present causes no problem.
No need for action.
