### ISSUE TITLE
Package with imports containing '!' character commits incorrect .st file

### ISSUE THREAD

**Issue by herby** [amber-smalltalk/amber#1156]
The .st files are in chunk format, which uses `!` as delimiter and if actual '!' char is present, it must be escaped as `!!`. If imports contain '!' somewhere, the output in .st file does not escape these.

**Comment by sebastianconcept** [comment]
Makes sense. So for now if we use those in imports, we should escape them like `css!!blah..`, yes?

**Comment by herby** [comment]
Yes.

Sebastian Sastre wrote:
