### ISSUE TITLE
Transcript is IDE yet included among deploy packages

### ISSUE THREAD

**Issue by sebastianconcept** [amber-smalltalk/amber#1159]
today's master version has in `support/deploy.js`

```javascript
define([
    './helpers',
    'jquery',
    // --- packages of the core Amber begin here ---
    'amber_core/Kernel-Objects',
    'amber_core/Kernel-Classes',
    'amber_core/Kernel-Methods',
    'amber_core/Kernel-Collections',
    'amber_core/Kernel-Infrastructure',
    'amber_core/Kernel-Exceptions',
    'amber_core/Kernel-Transcript',
    'amber_core/Kernel-Announcements',
    'amber_core/Web'
    // --- packages of the core Amber end here ---
], function (amber) { return amber; });
```

Transcript is a non-core IDE feature, there is no added value in having it in deploy.

Also Announcements and Web can be libraries as no all Amber apps use Announcements nor Web so we are taxing those users for no good reason.

**Comment by herby** [comment]
And there is more. ErrorHandler, Finder, ... Those are all _services_ of the platform and ate supposed to be there, at any time. Tjey are mostly bound to the IDE uf one is present, but they have an IDEless equivalent as well.

So no, Transcript won't go away, it is part of the core.

Web was already discussed on ML.

Announcements may seems like another optional feature, technically they are (technically, though, anything beyond they minimum needed to implement Metaclass loop is). OTOH, they are de facto way how to signal events in Smalltalk, especially Pharo which is the reference implementation. So I think it is good to tax users on this matter to not pudhing them to create plethora of different announcement systems but instead, opinionated, give them this one as The one. They are free not to use it, if it is their conscioya decision. But they must to that first.

**Comment by sebastianconcept** [comment]
I didn't formally measure but it doesn't look like intense code so it might be light enough to keep.
Also the Transcript package is just a couple of methods writing to console and not IDE resulting in something convenient for all cases.

There is one question I have regarding to:
```smalltalk
show: anObject
"Smalltalk objects should have no trouble displaying themselves on the Transcript; Javascript objects don't know how, so must be wrapped in a JSObectProxy."
<console.log(String($recv(anObject)._asString()))>
```

in the Chrome and other browser's console not using the _asString() there might actually be better since they can provide inspection. In the backend might be needed though.

Do you know if we can make it detect if it's on node or a browser so it can be smart and use it or not in each case?

**Comment by herby** [comment]
Transcript show: in IDE also does not write an object in inspectable state.

If you want thay, there should probably be an API for that that works transparently in all contexts.

**Comment by sebastianconcept** [comment]
Lately I was wondering about the value of Transcript in Amber because I'm not using it since a long ago.
For me the console is better.
How is it for you? what do you use more often?

**Comment by hhzl** [comment]
I use the Transcript. What is better about the console?

**Comment by sebastianconcept** [comment]
@hhzl the printing and inspection in general but specially when interacting with JavaScript.

Presuming that you are in a page where you have Amber and you can see a rendered element with id `some-element`, do this:

`Transcript cr; show: '#some-element' asJQuery`

`console log: '#some-element' asJQuery`

And compare the quality of the feedback that you get in one case and the other.

**Comment by hhzl** [comment]
OK, you are right. I agree.

But Smalltalk scripts generating text output (Transcript show: ..) it
is still useful.

**Comment by herby** [comment]
Transcript is de-facto stdout for Smalltalk all over. So many code uses it. I think it won't go away (I remove Kernel-Transcript package though, and blended it with all other service in Platform-Services in recent commits). I would close this.

**Comment by sebastianconcept** [comment]
Sure, but I would not miss at all if the traditional Transcript widget disappears and gets implemented just routing show: to the console for the browser or terminal.

**Comment by herby** [comment]
It is, but IDE injects its own service implementation. Just reregister console implementation (exercise left to the reader ;-) ) and you are[1] there.

Herby

[1] should be. Not tried.

Sebastian Sastre wrote:
