### ISSUE TITLE
Problem re-building amber from scratch

### ISSUE THREAD

**Issue by blakemcbride** [amber-smalltalk/amber#1160]
Can't seem to re-build amber from scratch.  Here is the complete log:

blake@sony-linux-laptop ~ $ rm -rf amber.git
blake@sony-linux-laptop ~ $ git clone https://github.com/amber-smalltalk/amber.git amber.git
Cloning into 'amber.git'...
remote: Counting objects: 28324, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 28324 (delta 12), reused 0 (delta 0)
Receiving objects: 100% (28324/28324), 44.95 MiB | 1.51 MiB/s, done.
Resolving deltas: 100% (20593/20593), done.
Checking connectivity... done
blake@sony-linux-laptop ~ $ sudo npm install -g amber-cli grunt-cli bower
[sudo] password for blake: 
/usr/local/bin/grunt -> /usr/local/lib/node_modules/grunt-cli/bin/grunt
/usr/local/bin/amber -> /usr/local/lib/node_modules/amber-cli/support/amber-cli.js
/usr/local/bin/amberc -> /usr/local/lib/node_modules/amber-cli/support/amberc-cli.js
/usr/local/bin/bower -> /usr/local/lib/node_modules/bower/bin/bower
grunt-cli@0.1.13 /usr/local/lib/node_modules/grunt-cli
├── nopt@1.0.10 (abbrev@1.0.5)
├── resolve@0.3.1
└── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.1)

amber-cli@0.14.0 /usr/local/lib/node_modules/amber-cli
├── grunt-init-amber@0.14.3
├── amber@0.14.4
├── amber-dev@0.3.2 (amdefine@0.0.8, es6-promise@2.0.1, amd-config-builder@0.2.0)
└── grunt-init@0.3.2 (semver@1.0.14, colors@0.6.2, hooker@0.2.3, async@0.2.10, prompt@0.1.12, grunt@0.4.5, lodash@2.4.1)

bower@1.3.12 /usr/local/lib/node_modules/bower
├── is-root@1.0.0
├── junk@1.0.0
├── stringify-object@1.0.0
├── which@1.0.8
├── abbrev@1.0.5
├── chmodr@0.1.0
├── osenv@0.1.0
├── archy@0.0.2
├── opn@1.0.1
├── rimraf@2.2.8
├── bower-logger@0.2.2
├── lru-cache@2.5.0
├── bower-endpoint-parser@0.2.2
├── graceful-fs@3.0.5
├── lockfile@1.0.0
├── nopt@3.0.1
├── retry@0.6.0
├── tmp@0.0.23
├── q@1.0.1
├── request-progress@0.3.0 (throttleit@0.0.2)
├── semver@2.3.2
├── shell-quote@1.4.2 (array-filter@0.0.1, array-map@0.0.0, array-reduce@0.0.0, jsonify@0.0.0)
├── p-throttler@0.1.0 (q@0.9.7)
├── bower-json@0.4.0 (intersect@0.0.3, deep-extend@0.2.11, graceful-fs@2.0.3)
├── promptly@0.2.0 (read@1.0.5)
├── fstream@1.0.4 (inherits@2.0.1)
├── chalk@0.5.0 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── bower-config@0.5.2 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1)
├── fstream-ignore@1.0.2 (inherits@2.0.1, minimatch@2.0.1)
├── tar-fs@0.5.2 (pump@0.3.5, tar-stream@0.4.7)
├── decompress-zip@0.0.8 (nopt@2.2.1, mkpath@0.1.0, touch@0.0.2, readable-stream@1.1.13, binary@0.3.0)
├── glob@4.0.6 (inherits@2.0.1, once@1.3.1, minimatch@1.0.0)
├── request@2.42.0 (caseless@0.6.0, json-stringify-safe@5.0.0, aws-sign2@0.5.0, forever-agent@0.5.2, stringstream@0.0.4, oauth-sign@0.4.0, tunnel-agent@0.4.0, qs@1.2.2, node-uuid@1.4.2, mime-types@1.0.2, form-data@0.1.4, http-signature@0.10.1, bl@0.9.4, tough-cookie@0.12.1, hawk@1.1.1)
├── bower-registry-client@0.2.3 (graceful-fs@2.0.3, request-replay@0.2.0, lru-cache@2.3.1, async@0.2.10, mkdirp@0.3.5, request@2.51.0)
├── cardinal@0.4.0 (redeyed@0.4.4)
├── mout@0.9.1
├── update-notifier@0.2.0 (semver-diff@0.1.0, string-length@0.1.2, latest-version@0.2.0, configstore@0.3.2)
├── inquirer@0.7.1 (figures@1.3.5, through@2.3.6, mute-stream@0.0.4, readline2@0.1.1, lodash@2.4.1, cli-color@0.3.2, rx@2.3.25)
├── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
└── insight@0.4.3 (object-assign@1.0.0, async@0.9.0, chalk@0.5.1, lodash.debounce@2.4.1, os-name@1.0.3, tough-cookie@0.12.1, configstore@0.3.2, inquirer@0.6.0)
blake@sony-linux-laptop ~ $ cd amber.git
blake@sony-linux-laptop ~/amber.git $ npm install
grunt-execute@0.2.2 node_modules/grunt-execute

pegjs@0.8.0 node_modules/pegjs

grunt-contrib-clean@0.6.0 node_modules/grunt-contrib-clean
└── rimraf@2.2.8

requirejs@2.1.16 node_modules/requirejs

amber-dev@0.3.2 node_modules/amber-dev
├── amdefine@0.0.8
├── es6-promise@2.0.1
└── amd-config-builder@0.2.0 (findit@1.2.0, lodash@2.4.1)

grunt@0.4.5 node_modules/grunt
├── which@1.0.8
├── dateformat@1.0.2-1.2.3
├── eventemitter2@0.4.14
├── getobject@0.1.0
├── rimraf@2.2.8
├── colors@0.6.2
├── async@0.1.22
├── grunt-legacy-util@0.2.0
├── hooker@0.2.3
├── exit@0.1.2
├── nopt@1.0.10 (abbrev@1.0.5)
├── lodash@0.9.2
├── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)
├── coffee-script@1.3.3
├── glob@3.1.21 (inherits@1.0.0, graceful-fs@1.2.3)
├── underscore.string@2.2.1
├── iconv-lite@0.2.11
├── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.1)
├── js-yaml@2.0.5 (argparse@0.1.16, esprima@1.0.4)
└── grunt-legacy-log@0.1.1 (underscore.string@2.3.3, lodash@2.4.1)

grunt-contrib-jshint@0.11.0 node_modules/grunt-contrib-jshint
├── hooker@0.2.3
└── jshint@2.6.0 (strip-json-comments@1.0.2, underscore@1.6.0, exit@0.1.2, minimatch@1.0.0, shelljs@0.3.0, cli@0.6.5, console-browserify@1.1.0, htmlparser2@3.8.2)
blake@sony-linux-laptop ~/amber.git $ bower install
bower jquery#>=1.7.0 <2.1.0     cached git://github.com/jquery/jquery.git#2.0.3
bower jquery#>=1.7.0 <2.1.0   validate 2.0.3 against git://github.com/jquery/jquery.git#>=1.7.0 <2.1.0
bower jquery#>=1.7.0 <2.1.0    install jquery#2.0.3

jquery#2.0.3 bower_components/jquery
blake@sony-linux-laptop ~/amber.git $ mkdir my
blake@sony-linux-laptop ~/amber.git $ git clone https://github.com/amber-smalltalk/helios.git my/helios
Cloning into 'my/helios'...
remote: Counting objects: 664, done.
remote: Total 664 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (664/664), 936.26 KiB | 1.17 MiB/s, done.
Resolving deltas: 100% (419/419), done.
Checking connectivity... done
blake@sony-linux-laptop ~/amber.git $ cd my/helios
blake@sony-linux-laptop ~/amber.git/my/helios $ bower install
bower jquery#>=1.7.0            cached git://github.com/jquery/jquery.git#2.1.3
bower jquery#>=1.7.0          validate 2.1.3 against git://github.com/jquery/jquery.git#>=1.7.0
bower codemirror#^4.7.0         cached git://github.com/marijnh/CodeMirror.git#4.12.0
bower codemirror#^4.7.0       validate 4.12.0 against git://github.com/marijnh/CodeMirror.git#^4.7.0
bower showdown#^0.3.1           cached git://github.com/showdownjs/showdown.git#0.3.4
bower showdown#^0.3.1         validate 0.3.4 against git://github.com/showdownjs/showdown.git#^0.3.1
bower jquery-ui#>=1.9.2         cached git://github.com/components/jqueryui.git#1.11.2
bower jquery-ui#>=1.9.2       validate 1.11.2 against git://github.com/components/jqueryui.git#>=1.9.2
bower amber#>=0.13.2            cached git://github.com/amber-smalltalk/amber.git#0.14.4
bower amber#>=0.13.2          validate 0.14.4 against git://github.com/amber-smalltalk/amber.git#>=0.13.2
bower bootstrap2.3.2#^2.3.2     cached git://github.com/alonisser/bower-bootstrap-2.3.2-legacy.git#2.3.2
bower bootstrap2.3.2#^2.3.2   validate 2.3.2 against git://github.com/alonisser/bower-bootstrap-2.3.2-legacy.git#^2.3.2
bower require-css#^0.1.2        cached git://github.com/guybedford/require-css.git#0.1.8
bower require-css#^0.1.2      validate 0.1.8 against git://github.com/guybedford/require-css.git#^0.1.2
bower jquery-ui#>=1.9.2            new version for git://github.com/components/jqueryui.git#>=1.9.2
bower jquery-ui#>=1.9.2        resolve git://github.com/components/jqueryui.git#>=1.9.2
bower jquery-ui#>=1.9.2       download https://github.com/components/jqueryui/archive/1.11.3.tar.gz
bower jquery#>=1.8.0 <2.1.0     cached git://github.com/jquery/jquery.git#2.0.3
bower jquery#>=1.8.0 <2.1.0   validate 2.0.3 against git://github.com/jquery/jquery.git#>=1.8.0 <2.1.0
bower jquery-ui#>=1.9.2        extract archive.tar.gz
bower jquery-ui#>=1.9.2       resolved git://github.com/components/jqueryui.git#1.11.3
bower jquery#>=1.8.0 <2.1.0    install jquery#2.0.3
bower showdown#^0.3.1          install showdown#0.3.4
bower bootstrap2.3.2#^2.3.2    install bootstrap2.3.2#2.3.2
bower amber#>=0.13.2           install amber#0.14.4
bower codemirror#^4.7.0        install codemirror#4.12.0
bower require-css#^0.1.2       install require-css#0.1.8
bower jquery-ui#>=1.9.2        install jquery-ui#1.11.3

jquery#2.0.3 bower_components/jquery

showdown#0.3.4 bower_components/showdown

bootstrap2.3.2#2.3.2 bower_components/bootstrap2.3.2
└── jquery#2.0.3

amber#0.14.4 bower_components/amber
└── jquery#2.0.3

codemirror#4.12.0 bower_components/codemirror

require-css#0.1.8 bower_components/require-css

jquery-ui#1.11.3 bower_components/jquery-ui
└── jquery#2.0.3
blake@sony-linux-laptop ~/amber.git/my/helios $ cd ../..
blake@sony-linux-laptop ~/amber.git $ git clone https://github.com/amber-smalltalk/amber-attic.git my/amber-attic
Cloning into 'my/amber-attic'...
remote: Counting objects: 80, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 80 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (80/80), done.
Checking connectivity... done
blake@sony-linux-laptop ~/amber.git $ grunt devel
Running "amdconfig:amber" (amdconfig) task

Done, without errors.
blake@sony-linux-laptop ~/amber.git $ grunt amberc
Running "amberc:amber" (amberc) task
Reading: src/Kernel-Objects.st
Reading: src/Kernel-Classes.st
Reading: src/Kernel-Methods.st
Reading: src/Kernel-Collections.st
Reading: src/Kernel-Infrastructure.st
Reading: src/Kernel-Exceptions.st
Reading: src/Kernel-Transcript.st
Reading: src/Kernel-Announcements.st
Reading: src/Kernel-ImportExport.st
Reading: src/Compiler-Exceptions.st
Reading: src/Compiler-Core.st
Reading: src/Compiler-AST.st
Reading: src/Compiler-IR.st
Reading: src/Compiler-Inlining.st
Reading: src/Compiler-Semantic.st
Reading: src/Compiler-Interpreter.st
Reading: src/Web.st
Reading: src/SUnit.st
Reading: src/Kernel-Tests.st
Reading: src/Compiler-Tests.st
Reading: src/SUnit-Tests.st
Compiling ProtoObject as a subclass of `nil`. A dependency might be missing.
[Error: Compiler error in section:
BrowserInterface methodsFor: 'actions'

while processing chunk:
ajax: anObject
	^ jQuery ajax: anObject

Unknown Variable error: jQuery is not defined]

Running "amberc:cli" (amberc) task
Reading: external/amber-cli/src/AmberCli.st
Writing program file: external/amber-cli/support/amber-cli.js

Running "amberc:dev" (amberc) task
Reading: external/amber-dev/lib/Test.st

Running "amberc:test_runner" (amberc) task
Reading: node_modules/amber-dev/lib/Test.st
Writing program file: test_runner.js

Done, without errors.
blake@sony-linux-laptop ~/amber.git $

**Comment by blakemcbride** [comment]
I am still seeing the following error:

Compiling ProtoObject as a subclass of `nil`. A dependency might be missing.

Thanks!

**Comment by herby** [comment]
Blake McBride wrote:
> I am still seeing the following error:
>
> Compiling ProtoObject as a subclass of |nil|. A dependency might be 
> missing.

That's anticipated (ProtoObject _is_ subclass of nil). Problem would be if you get more of them (then, you probably really miss a dependency somewhere).
