### ISSUE TITLE
PackageStateObserver seems to be unused orphan

### ISSUE THREAD

**Issue by herby** [amber-smalltalk/amber#1162]
Last big update on 5f7d139 @NicolasPetton, last small update on 6443548 @seandenigris.

No references found in code, though. Could it be deleted?

**Comment by philippeback** [comment]
Isn't it used in Helios?

On Tue, Feb 24, 2015 at 2:15 PM, Herbert Vojčík <notifications@github.com>
wrote:

> Last big update on 5f7d139
> <https://github.com/amber-smalltalk/amber/commit/5f7d139e5507bea2d72c6407ab50bfac0ebc2e37>
> @NicolasPetton <https://github.com/NicolasPetton>, last small update on
> 6443548
> <https://github.com/amber-smalltalk/amber/commit/644354851932a214e6876bfc66f71be6daaa3f67>
> @seandenigris <https://github.com/seandenigris>.
>
> No references found in code, though. Could it be deleted?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amber-smalltalk/amber/issues/1162>.
>



-- 
---
Philippe Back
Visible Performance Improvements
Mob: +32(0) 478 650 140 | Fax: +32 (0) 70 408 027
Mail:phil@highoctane.be | Web: http://philippeback.eu
Blog: http://philippeback.be | Twitter: @philippeback
Youtube: http://www.youtube.com/user/philippeback/videos

High Octane SPRL
rue cour Boisacq 101 | 1301 Bierges | Belgium

Pharo Consortium Member - http://consortium.pharo.org/
Featured on the Software Process and Measurement Cast -
http://spamcast.libsyn.com
Sparx Systems Enterprise Architect and Ability Engineering EADocX Value
Added Reseller

**Comment by herby** [comment]
No afaict. Did a search there as well.

Philippe Back wrote:
> Isn't it used in Helios?
>
> On Tue, Feb 24, 2015 at 2:15 PM, Herbert Vojčík <notifications@github.com>
> wrote:
>
> > Last big update on 5f7d139
> > 
> <https://github.com/amber-smalltalk/amber/commit/5f7d139e5507bea2d72c6407ab50bfac0ebc2e37>
> > @NicolasPetton <https://github.com/NicolasPetton>, last small update on
> > 6443548
> > 
> <https://github.com/amber-smalltalk/amber/commit/644354851932a214e6876bfc66f71be6daaa3f67>
> > @seandenigris <https://github.com/seandenigris>.
> >
> > No references found in code, though. Could it be deleted?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/amber-smalltalk/amber/issues/1162>.
> >
>
>
>
> -- 
> ---
> Philippe Back
> Visible Performance Improvements
> Mob: +32(0) 478 650 140 | Fax: +32 (0) 70 408 027
> Mail:phil@highoctane.be | Web: http://philippeback.eu
> Blog: http://philippeback.be | Twitter: @philippeback
> Youtube: ht
tp://www.youtube.com/user/philippeback/videos

**Comment by seandenigris** [comment]
It does seem to be still used in Helios. If I put a halt in PackageStateObserver>>#onProtocolModification: (which marks packages as dirty) and rename a protocol, the halt is triggered.

**Comment by herby** [comment]
Strange I did not find it by searching... I must try once more.

Sean DeNigris wrote:

**Comment by seandenigris** [comment]
It gets triggered by an announcement, so maybe there's no direct reference?

**Comment by herby** [comment]
There must be a reference at least when it's created... or is it a singleton created by class-side initialize?!

Sean DeNigris wrote:

**Comment by herby** [comment]
Ah.

```smalltalk
!PackageStateObserver class methodsFor: 'initialization'!

initialize
	self current observeSystem
! !
```

It seems so. Closing.

**Comment by seandenigris** [comment]
I was just viewing the same method :)
