### ISSUE TITLE
PlatformInterface doc typo

### ISSUE THREAD

**Issue by davidgraham** [amber-smalltalk/amber#1167]
The ajax example in the doc for Platform interface is missing single quotes around dataType.  Should read:

PlatformInterface ajax: #{
    'url' -> '/patch.js'. 'type' -> 'GET'. 'dataType'->'script'
}.

**Comment by herby** [comment]
Ok, include a PR.

**Comment by herby** [comment]
Closing as `ajax:` is deprecated.
