### ISSUE TITLE
Add local file-saving feature to use Amber for locally hosted rapid prototypes and experiments

### ISSUE THREAD

**Issue by Basilmir** [amber-smalltalk/amber#1168]
*Initial thoughts*
I would like to discuss an interesting use case for Amber. The typical development setup for an Amber project is on top of a Server running node.js. But the entire app actually runs in the Web Browser and only communicates with the Server when you commit the code.

**I want to run it locally**. Imagine commiting from the Web Browser directly to the file system. You use amber-cli to create the project directory structure and instead of starting the app in, for example, WEBrick all you do is *open index.html*.

Example use case:
Open a terminal.
git clone https://github.com/amber-smalltalk/amber-website.git
cd amber-website
*open index.html
*get work done and Commit the package in Helios IDE
git commit -m "that was easy"
git push origin master
**Done**

**How would this work?**

After careful consideration on the mailing list, we've concluded that it's best to implement this feature in a similar fashion *but* preserving the current Amber structure and Version Control System. Essentially leaving the project structure unchanged but instead adding this capability to the IDE itself.

Amber development take place on the Client in a Web Browser. Normally the IDE functions independently of the server, with the exception of the Commit Package command which initiates a POST/PUT uploading the .st source files and the .js compiled version of the source.

Method 1 (Herby V.):
**This is where this project comes into play** Apparently finding a place where "ajax:" is called to do a HTTP PUT and make it use "saveFile:" if the protocol is file:// (the app was opened locally) 

Possible complications:
There might be complications as this uses require.to URL IIRC and we don't know what it returns for file://

Method X (Mir S. -  this is more like a scenario description, I'm not a programmer and I can only see the end result, not the implementation)
But wait there's more, here is where it becomes really interesting. Tiddlywiki goes even further:

Q: Yes, yes but wouldn't it be nice if it could save itself automagically every time I edit a method, or every time I commit a package?
A: Not so easy... But it's already been done. 
Believe it or not they even have Automatic Saving. but for that you need Firefox with the TiddlyFox https://addons.mozilla.org/ro/firefox/addon/tiddlyfox/ extension installed.
Now when you open your local file with Firefox (+TiddlyFox) you are asked if you want to enable local file saving for this file (it asks for every new file and remembers the ones you already added)
Done. Now Click the “+” sign to add a new Tiddler, edit it, click the checkmark to save it and now the top right corner lights up with a notification. Wiki saved.

* this is how TiddlyFox the extensions sets up an environment to save the file https://github.com/TiddlyWiki/TiddlyFox/blob/6cf9c9ee6e128a681548529316b3d31a8362fe0d/content/overlay.js#L84

To be continued, I will try to summarize all my information with references where possible.
Tried to add this issue to add a bounty on https://www.bountysource.com/teams/amber-smalltalk/issues
thinking they were linked somehow, but apparently they aren't. I probably need to be added to the team.

**Comment by herby** [comment]
Marking "won't fix" as this is not an issue but as you @Basilmir said yourself, a discussion.
One there will be a clear outcome (like modify transport to do saveFile when file:// is a protocol), put it to issue on its own.

Just a personal though: too long. no one will read it. remove all the tiddlywiki stuff.

**Comment by Basilmir** [comment]
Ok I will edit it and break it down into bite sized issues. 

Can't figure out bountysource, there is an amber-smalltalk team there but it's unclaimed, and issues here don't seem to sync?

https://www.bountysource.com/teams/amber-smalltalk/

**Comment by herby** [comment]
Don't know, maybe it needs some setup at our side...

Mircea S. wrote:

**Comment by jbshirk** [comment]
This topic is of great interest to me. I've been watching Amber as my
favorite candidate to develop a mobile app that must be able to function as
standalone, that is, without continuous internet connectivity. (It's
primary purpose is to be the interface to an arduino via BLE). I've been
wondering whether a running local database instance would serve for
persistence.


On Wed, Apr 1, 2015 at 10:04 AM, Mircea S. <notifications@github.com> wrote:

> Ok I will edit it and break it down into bite sized issues.
>
> Can't figure out bountysource, there is an amber-smalltalk team there but
> it's unclaimed, and issues here don't seem to sync?
>
> https://www.bountysource.com/teams/amber-smalltalk/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amber-smalltalk/amber/issues/1168#issuecomment-88494928>
> .
>



-- 

Gmail is unsecure. Why? See: EFF Surveillance Self-Defense Project
<https://ssd.eff.org/tech/email>

My preferred secure email address: infomaniac(at)i2pmail(dot)org
(For more information, please see: About I2P <http://www.i2p2.de/intro.html>
)

If you prefer to send to this gmail account, consider using
https://www.mailpile.is

My Public key:
https://pgp.mit.edu/pks/lookup?op=vindex&search=0x8726E59217F0E6F9

**Comment by Basilmir** [comment]
I think you can start by claiming the boutysource team here. Make sure you choose to login with your GitHub account so they can verify you are part of the core team. https://www.bountysource.com/teams/amber-smalltalk/settings

**Comment by Basilmir** [comment]
Oh great! Do you know Javascript or Amber so we can start?



Pe 1 apr. 2015, la 17:31, Joe <notifications@github.com> a scris:

> This topic is of great interest to me. I've been watching Amber as my
> favorite candidate to develop a mobile app that must be able to function as
> standalone, that is, without continuous internet connectivity. (It's
> primary purpose is to be the interface to an arduino via BLE). I've been
> wondering whether a running local database instance would serve for
> persistence.
> 
>

**Comment by herby** [comment]
@Basilmir bountysource should be set up for amber-smalltalk/amber and amber-smalltalk/helios projects.

**Comment by herby** [comment]
In fact, I think this is a good piece for a jquery plugin - to make `jquery.ajax` work with `GET` as well as `PUT` when protocol is `file://`. This solution is generic and to solve this issue (at least the basic part of it), it would need just loading that plugin (I did not find such plugin).

**Comment by jbshirk** [comment]
I had thought I would use EvoThings, which is an HTML5 + javascript-based
framework that works with Apache Cordova -> PhoneGap (to access BLE and
phone sensors) but EvoThings won’t function without live connectivity. So I
am watching alternatives to EvoThings that that may work in standalone mode
offline:

Amber
CocoonJS
Crosswalk
Meteor
Derby
Node-webkit (confirmed no standalone)
AngularJS
io.js

I have not confirmed that any of them can work in this use case, so I am
not committed to Amber, though I would love to be certain that it could do
the job, as I would prefer to see Amber a showcase for a better
alternative.

In any case, I am not an advanced programmer, so I would not be the go-to
person for developing a data backend any time soon.

**Comment by herby** [comment]
Closing. Added #1176 as a pinpointed feature request.

**Comment by Basilmir** [comment]
Made some progress on the subject, but it's not what anyone expects.

If you're on a Mac you can use this free app on the App Store called WebDAVNavServer:
https://itunes.apple.com/us/app/webdavnav-server/id747482894

It essentially lets you run a webdav server off the directory where the app is located, quite similar to 'amber serve' but very useful for people doing development on a machine that they don't install the entire toolchain on.

**Comment by herby** [comment]
I have looked for save file API and it seems there isn't any, so this all is a bogus, maybe.

Mircea S. wrote:

**Comment by Basilmir** [comment]
You're right, it's very hard to do. Modern browsers, at most, let you get .css an .js files in the current folder but that's it, no saving and so on.

There's another window of opportunity, this guy developed a TiddlyChromeSaver which again leverages some Browser extension of some sort for "help" with file system access. 

https://groups.google.com/forum/#!msg/tiddlywiki/nKxU_ixVKTI/sjZxdLpLjwwJ

You can apparently install apps inside Chrome, made up of an .arx and .js. You then visit chrome://apps/ or click the top left Apps button in the first window and launch this app.

**Comment by psvensson** [comment]
But wouldn't it be possible to start a node web-server from grunt, enable
CORS on it, send updates back to it using plain Ajax and have the server
update (or generate) the .st files?

Cheers,
PS

On Tue, Aug 18, 2015 at 8:15 PM, Mircea S. <notifications@github.com> wrote:

> You're right, it's very hard to do. Modern browsers, at most, let you get
> .css an .js files in the current folder but that's it, no saving and so on.
>
> There's another window of opportunity, this guy developed a
> TiddlyChromeSaver which again leverages some Browser extension of some sort
> for "help" with file system access.
>
> https://groups.google.com/forum/#!msg/tiddlywiki/nKxU_ixVKTI/sjZxdLpLjwwJ
>
> You can apparently install apps inside Chrome, made up of an .arx and .js.
> You then visit chrome://apps/ or click the top left Apps button in the
> first window and launch this app.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amber-smalltalk/amber/issues/1168#issuecomment-132305313>
> .
>



-- 
"Easily the funniest and most original programming competition around";
http://www.escapedevnull.com

http://se.linkedin.com/in/petersvensson (LinkedIn)
https://plus.google.com/u/0/109826099655556298824
<https://plus.google.com/u/0/109826099655556298824/posts> (Google+)
http://twitter.com/psvensson (@psvensson)

**Comment by herby** [comment]
??? We already save things on the node server. We start it using `amber serve`. This was about server-less solution using file system. There is no point to create yet another server.

psvensson wrote:
> But wouldn't it be possible to start a node web-server from grunt, enable
> CORS on it, send updates back to it using plain Ajax and have the server
> update (or generate) the .st files?
>
> Cheers,
> PS
>
> On Tue, Aug 18, 2015 at 8:15 PM, Mircea S. <notifications@github.com> 
> wrote:
>
> > You're right, it's very hard to do. Modern browsers, at most, let 
> you get
> > .css an .js files in the current folder but that's it, no saving and 
> so on.
> >
> > There's another window of opportunity, this guy developed a
> > TiddlyChromeSaver which again leverages some Browser extension of 
> some sort
> > for "help" with file system access.
> >
> > 
> https://groups.google.com/forum/#!msg/tiddlywiki/nKxU_ixVKTI/sjZxdLpLjwwJ
> >
> > You can apparently install apps inside Chrome, ma
de up of an .arx

**Comment by psvensson** [comment]
Ah, my bad. Sorry to bare in before reading through the thread properly.

On Tue, Aug 18, 2015 at 10:33 PM, Herbert Vojčík <notifications@github.com>
wrote:

> ??? We already save things on the node server. We start it using `amber
> serve`. This was about server-less solution using file system. There is no
> point to create yet another server.
>
> psvensson wrote:
> > But wouldn't it be possible to start a node web-server from grunt, enable
> > CORS on it, send updates back to it using plain Ajax and have the server
> > update (or generate) the .st files?
> >
> > Cheers,
> > PS
> >
> > On Tue, Aug 18, 2015 at 8:15 PM, Mircea S. <notifications@github.com>
> > wrote:
> >
> > > You're right, it's very hard to do. Modern browsers, at most, let
> > you get
> > > .css an .js files in the current folder but that's it, no saving and
> > so on.
> > >
> > > There's another window of opportunity, this guy developed a
> > > TiddlyChromeSaver which again leverages some Browser extension of
> > some sort
> > > for "help" with file system access.
> > >
> > >
> >
> https://groups.google.com/forum/#!msg/tiddlywiki/nKxU_ixVKTI/sjZxdLpLjwwJ
> > >
> > > You can apparently install apps inside Chrome, ma
> de up of an .arx
> > and .js.
> > > You then visit chrome://apps/ or click the top left Apps button in the
> > > first window and launch this app.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > >
> > <
> https://github.com/amber-smalltalk/amber/issues/1168#issuecomment-132305313
> >
> > > .
> > >
> >
> >
> >
> > --
> > "Easily the funniest and most original programming competition around";
> > http://www.escapedevnull.com
> >
> > http://se.linkedin.com/in/petersvensson (LinkedIn)
> > https://plus.google.com/u/0/109826099655556298824
> > <https://plus.google.com/u/0/109826099655556298824/posts> (Google+)
> > http://twitter.com/psvensson (@psvensson)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/amber-smalltalk/amber/issues/1168#issuecomment-132325638
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amber-smalltalk/amber/issues/1168#issuecomment-132342202>
> .
>



-- 
"Easily the funniest and most original programming competition around";
http://www.escapedevnull.com

http://se.linkedin.com/in/petersvensson (LinkedIn)
https://plus.google.com/u/0/109826099655556298824
<https://plus.google.com/u/0/109826099655556298824/posts> (Google+)
http://twitter.com/psvensson (@psvensson)

**Comment by jbshirk** [comment]
using https://github.com/ipfs/js-ipfs we will soon be able to read/write via the ipfs protocol.

**Comment by psvensson** [comment]
Sweet!  Will check out.
