### ISSUE TITLE
Package fails to commit in Safari

### ISSUE THREAD

**Issue by JupiterJones** [amber-smalltalk/amber#1184]
Amber 0.14.14 loads in Safari, but packages don't commit.
- Legacy IDE silently fails
- Helios throws exception... 
[object XMLHttpRequestConstructor] does not understand #new
in method
BrowserPlatform>>newXhr

**Comment by herby** [comment]
@JupiterJones Do `bower install "amber#master"` in a failing project, load it again and confirm if it helped / reopen if not.

**Comment by JupiterJones** [comment]
@herby yes that worked. cheers!

**Comment by herby** [comment]
Released as `0.14.15`.
