### ISSUE TITLE
Date equality comparison fails for equal dates

### ISSUE THREAD

**Issue by JupiterJones** [amber-smalltalk/amber#1185]
= (in Date) reverts to == (in ProtoObject) so an equality comparison for equal dates returns false. 

= aDate
	^ (aDate isKindOf: Date) and: [ self time == aDate time ]

**Comment by herby** [comment]
Jupiter Jones wrote:
> = (in Date) reverts to == (in ProtoObject) so an equality comparison 
> for equal dates returns false.
>
> = aDate
> ^ (aDate isKindOf: Date) and: [ self time == aDate time ]

This is more an issue in tracker.

isKindOf: invites problems and makes a = b clearly different from b = a.
I would write ^ (aDate class == self class) and: [ ... ]

**Comment by herby** [comment]
Next time @JupiterJones you can send a PR so you can improve your position in https://github.com/amber-smalltalk/amber/graphs/contributors... ;-)
