### ISSUE TITLE
-1 + 2 yields -3 in deploy mode

### ISSUE THREAD

**Issue by kryshen** [amber-smalltalk/amber#1215]
The expression

    console log: -1 + 2.

properly prints 1 to the console in development mode, but prints -3 after compiling with 'grunt deploy'.

**Comment by kryshen** [comment]
Adding 'optimize: "none"' to requirejs deploy options solved the problem, so it is probably a bug in requirejs optimizer.

**Comment by herby** [comment]
Thanks. It would be helpful if you could pinpoint to minimal example and issue it as bug for requirejs optimizer.

kryshen wrote:

**Comment by herby** [comment]
"Won't fix" as it's an upstream bug. Keeping open until it's fixed.

**Comment by kryshen** [comment]
It appears that by default RequireJS uses outdated Uglify 1.x that is
known to break code.  They plan to switch to using Uglify2 by default in
a future release: https://github.com/jrburke/r.js/issues/883

Setting 'optimize: "uglify2"' fixed the problem.  Perhaps that should be
added to the template for now.

**Comment by herby** [comment]
PR welcome (repo grunt-init-amber) ;-)

kryshen wrote:
> It appears that by default RequireJS uses outdated Uglify 1.x that is
> known to break code. They plan to switch to using Uglify2 by default in
> a future release: https://github.com/jrburke/r.js/issues/883
>
> Setting 'optimize: "uglify2"' fixed the problem. Perhaps that should be
> added to the template for now.
>
> Herbert Vojčík <notifications@github.com> writes:
>
> > Thanks. It would be helpful if you could pinpoint to minimal example 
> and issue it as bug for requirejs optimizer.
> >
> > kryshen wrote:
> >> Adding 'optimize: "none"' to requirejs deploy options solved the
> >> problem, so it is probably a bug in requirejs optimizer.
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> 
> <https://github.com/amber-smalltalk/amber/issues/1215#issuecomment-174652141>.
> >>
> >
> >
> > ---
> > Reply to this email directly or view it on GitHub:
> > 
> https://github.com/amber-smalltalk/amber/iss
ues/1215#issuecomment-174654745

**Comment by herby** [comment]
BTW is uglify2 present by default? Or it needs to be installed separately?

**Comment by kryshen** [comment]
I replied by email yesterday, but id did not appear here.

I'm not deeply familiar with JavaScript package management, but It looks like both versions of Uglify are bundled into RequireJS.
