### ISSUE TITLE
Pressing InspectIt in worspace/debugger gives DNU #onDblClick

### ISSUE THREAD

**Issue by macta** [amber-smalltalk/amber#1217]
In  0.15.x in a  workspace, if I click “printit” on 5 + 1, I get an error "nil does not understand #onDblClick"

I had this is 0.15, and confirmed its also present in 0.15.1
OS: osx 10.11.3
Browser: Safari, Firefox, Chrome

Other users have confirmed this behavior.

It looks like the method:

HLInspectorVariablesWidget>>renderContentOn: html
	self renderHeadOn: html.
	super renderContentOn: html.
	self wrapper onDblClick: [ self dive ]

**Comment by macta** [comment]
In the debugger, if you click on this method (in the stack trace) and click BrowseIt - you also get another error:

"Parse error on line undefined column undefined : Unexpected character "

behind the debugger - so something seems messed up.

**Comment by herby** [comment]
Does InspectIt work in legacy IDE? If yes, this is likely a helios problem (and should be filed under helios repo).
There were some changes involving self wrapper IIRC, they may be the cause.

Dňa 29. februára 2016 14:19:10 CET používateľ Tim Mackinnon <notifications@github.com> napísal:

**Comment by herby** [comment]
This should be different issue - this happens when there's an exception in code used by parser to build an AST.

Dňa 29. februára 2016 14:20:54 CET používateľ Tim Mackinnon <notifications@github.com> napísal:

**Comment by herby** [comment]
It would be nice to catch more about that parser problem, basically, interesting is what was parsed to get an error, for which you may put some `console dir: foo` or `console.dir(foo)` (based on if it's ST or JS) into `SmalltalkImage >> parse:`.

**Comment by paulwilke** [comment]
I can confirm this. In legacy IDE inspect works, so it is a Helios bug
