### ISSUE TITLE
Commit package broken in osx Safari

### ISSUE THREAD

**Issue by macta** [amber-smalltalk/amber#1218]
When I add the class “FormExample” into the same package created by amber init - and do cmd-s and then press the commit button -  I get the error “a problem occurred with this web page” and then safari gives a “safari web content quit unexepecdely” error (and the stack trace in safari is in the Javascript process:

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000560
Exception Note:        EXC_CORPSE_NOTIFY
“
This is on OS X 10.1.3 (El Capitain). with Safari 9.0.3 (the latest that comes with OSX).

This occurs in both Helios and Legacy ide's.

Tim

**Comment by herby** [comment]
It's a Safari problem. Try another browser.

**Comment by herby** [comment]
Feel free to reopen when Safari crash itself is fixed by Apple and there are still error on JS level.
