### ISSUE TITLE
Rename ClassCategoryReader to ClassProtocolReader?

### ISSUE THREAD

**Issue by mkroehnert** [amber-smalltalk/amber#710]
`Class>>category` is deprecated in favor of `Class>>package` so we should probably rename `ClassCategoryReader` to `ClassPackageReader`.

**Comment by herby** [comment]
`PackageReader` should be enough.

**Comment by herby** [comment]
Oh, it was not about reading a category of classes, but category of methods, so it should be `ClassProtocolReader`.
